"""训练器模块的懒加载公共导出。"""

from importlib import import_module

__all__ = [
    # 配置
    "TrainingConfig",
    "parse_training_config",
    "MetaConfig",
    "ModelConfig",
    "MultiViewConfig",
    "PredictorDiTConfig",
    "DataConfig",
    "OptimizationConfig",
    "PlannerConfig",
    "ProposalConfig",
    "NavSimConfig",
    "Bench2DriveConfig",
    "SegmentationConfig",
    "TrainConfig",
    "EMAConfig",
    "LossConfig",
    "RLConfig",
    "RewardConfig",
    "ValueGuidanceConfig",
    "DataAugConfig",
    "BudgetControllerConfig",
    # 分布式
    "setup_distributed",
    "setup_device",
    "get_local_rank",
    "is_main_process",
    # 模型
    "init_context_encoder",
    "init_encoder",
    "init_encoder_for_full_state_warmstart",
    "init_predictor",
    "init_predictor_for_ae",
    "init_segmentation_modules",
    "init_planner",
    "init_proposal_encoder",
    "configure_vjepa_encoder_trainability",
    "resolve_main_predictor_runtime_overrides",
    "should_save_main_encoder",
    "compile_models",
    "get_encoder_embed_dim",
    # 数据
    "create_transforms",
    "create_proposal_transforms",
    "create_train_dataloader",
    "create_val_dataloader",
    "create_validation_transforms",
    "calculate_iterations_per_epoch",
    # 优化器
    "create_optimizer_and_scheduler",
    "add_planner_param_groups",
    "add_encoder_param_groups",
    "wrap_ddp_models",
    "freeze_parameters",
    "log_trainable_parameters",
    # Checkpoint
    "wait_for_checkpoint_save",
    "load_state_dict_helper",
    "load_multiview_fusion_from_checkpoint",
    "load_pretrained_checkpoint",
    "save_training_checkpoint",
    "resume_from_checkpoint",
    "load_checkpoint",
    "setup_checkpoint_paths",
    "extract_portable_predictor_state",
    "extract_peft_predictor_state",
    "is_peft_wrapped",
    "load_predictor_peft_state",
    # EMA
    "create_momentum_scheduler",
    "create_ema_update_fn",
    "EMAUpdater",
    # 日志
    "setup_logging",
    "log_training_metrics",
    "log_epoch_summary",
    "log_validation_metrics",
    "log_predictor_camera_training_metrics",
    "log_predictor_validation_metrics",
    "log_training_summary",
    "log_open_loop_diagnostic_table",
    "build_validation_record",
    "is_better_open_loop_candidate",
    "OPEN_LOOP_SELECTION_RULE",
    "DEFAULT_LOG_COLUMNS",
    "DEFAULT_LOG_COMMENTS",
    # 训练循环
    "create_loss_meters",
    "init_training_loop",
    "is_epoch_validation_due",
    "get_next_batch",
    "load_clips",
    "maybe_run_gc",
    "TrainingTimer",
    "create_stage_timing_meters",
    "record_stage_timing",
    "log_stage_timing_summary",
    "resolve_timing_warmup_iters",
    "start_cuda_timing",
    "stop_cuda_timing",
    # RL
    "RolloutBatch",
    "RolloutBuffer",
    "compute_gae",
    "create_hugsim_env",
    "HUGSIMScenarioSpec",
    "HUGSIMScenarioManager",
    "HUGSIMObservationAdapter",
    "load_hugsim_scenarios",
    "validate_hugsim_scenarios",
    "get_action_bounds",
    "tensor_action_to_env",
    "rollout_info_to_metrics",
    "info_to_state_vector",
    "require_info_field",
    "build_status_feature_from_history",
    "build_state_history_tensor",
    "build_frame_history_tensor",
    "build_predictor_rollout_tensors",
    "frame_history_to_context_clip",
    "encode_context_clip",
    "planner_forward_from_z",
    "predictor_ar_rollout",
    "states_to_action_history",
    "compute_baseline_control",
    "compute_policy_mean",
]

_EXPORT_GROUPS = (
    (
        "config",
        (
            "Bench2DriveConfig",
            "BudgetControllerConfig",
            "DataAugConfig",
            "DataConfig",
            "EMAConfig",
            "LossConfig",
            "MetaConfig",
            "ModelConfig",
            "MongoRawConfig",
            "MultiViewConfig",
            "NavSimConfig",
            "OptimizationConfig",
            "PlannerConfig",
            "PredictorDiTConfig",
            "ProposalConfig",
            "RewardConfig",
            "RLConfig",
            "SegmentationConfig",
            "TrainConfig",
            "TrainingConfig",
            "ValueGuidanceConfig",
            "ValuePlanningConfig",
            "parse_training_config",
        ),
    ),
    (
        "distributed",
        ("get_local_rank", "is_main_process", "setup_device", "setup_distributed"),
    ),
    (
        "models",
        (
            "compile_models",
            "configure_vjepa_encoder_trainability",
            "get_encoder_embed_dim",
            "init_context_encoder",
            "init_encoder",
            "init_encoder_for_full_state_warmstart",
            "init_planner",
            "init_predictor",
            "init_predictor_for_ae",
            "init_proposal_encoder",
            "init_segmentation_modules",
            "resolve_main_predictor_runtime_overrides",
            "should_save_main_encoder",
        ),
    ),
    (
        "data",
        (
            "calculate_iterations_per_epoch",
            "create_proposal_transforms",
            "create_train_dataloader",
            "create_transforms",
            "create_val_dataloader",
            "create_validation_transforms",
        ),
    ),
    (
        "optimizer",
        (
            "add_encoder_param_groups",
            "add_planner_param_groups",
            "create_optimizer_and_scheduler",
            "freeze_parameters",
            "log_trainable_parameters",
            "wrap_ddp_models",
        ),
    ),
    (
        "checkpoint",
        (
            "extract_peft_predictor_state",
            "extract_portable_predictor_state",
            "is_peft_wrapped",
            "load_checkpoint",
            "load_multiview_fusion_from_checkpoint",
            "load_predictor_peft_state",
            "load_pretrained_checkpoint",
            "load_state_dict_helper",
            "resume_from_checkpoint",
            "save_training_checkpoint",
            "setup_checkpoint_paths",
            "wait_for_checkpoint_save",
        ),
    ),
    (
        "ema",
        ("EMAUpdater", "create_ema_update_fn", "create_momentum_scheduler"),
    ),
    (
        "logging",
        (
            "DEFAULT_LOG_COLUMNS",
            "DEFAULT_LOG_COMMENTS",
            "OPEN_LOOP_SELECTION_RULE",
            "build_validation_record",
            "is_better_open_loop_candidate",
            "log_epoch_summary",
            "log_open_loop_diagnostic_table",
            "log_predictor_camera_training_metrics",
            "log_predictor_validation_metrics",
            "log_training_metrics",
            "log_training_summary",
            "log_validation_metrics",
            "setup_logging",
        ),
    ),
    (
        "loop",
        (
            "TrainingTimer",
            "create_loss_meters",
            "create_stage_timing_meters",
            "get_next_batch",
            "init_training_loop",
            "is_epoch_validation_due",
            "load_clips",
            "log_stage_timing_summary",
            "maybe_run_gc",
            "record_stage_timing",
            "resolve_timing_warmup_iters",
            "start_cuda_timing",
            "stop_cuda_timing",
        ),
    ),
    ("rl_buffer", ("RolloutBatch", "RolloutBuffer", "compute_gae")),
    (
        "rl_hugsim_env",
        (
            "HUGSIMObservationAdapter",
            "HUGSIMScenarioManager",
            "HUGSIMScenarioSpec",
            "build_frame_history_tensor",
            "build_state_history_tensor",
            "build_status_feature_from_history",
            "create_hugsim_env",
            "get_action_bounds",
            "info_to_state_vector",
            "load_hugsim_scenarios",
            "require_info_field",
            "rollout_info_to_metrics",
            "tensor_action_to_env",
            "validate_hugsim_scenarios",
        ),
    ),
    (
        "rl_policy",
        (
            "build_predictor_rollout_tensors",
            "compute_baseline_control",
            "compute_policy_mean",
            "encode_context_clip",
            "frame_history_to_context_clip",
            "planner_forward_from_z",
            "predictor_ar_rollout",
            "states_to_action_history",
        ),
    ),
)

_EXPORT_MODULES = {name: f"{__name__}.{module_name}" for module_name, names in _EXPORT_GROUPS for name in names}


def __getattr__(name: str) -> object:
    """按需加载并缓存原有公共导出。"""

    module_name = _EXPORT_MODULES.get(name)
    if module_name is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    module = import_module(module_name)
    value = getattr(module, name)
    globals()[name] = value
    return value
